reviews:
  auto_review:
    enabled: true
  review_status: true
  request_changes_workflow: true
  high_level_summary: true
  poem: false

chat:
  auto_reply: true

early_access: true

knowledge_base:
  opt_out: false